# Generated by Django 5.0.3 on 2024-03-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gereradorGrafico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gereradorgrafico',
            name='DependenciaAdministrativa',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='gereradorgrafico',
            name='UnidadeGeografica',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='gereradorgrafico',
            name='localizacao',
            field=models.CharField(max_length=6),
        ),
    ]
