# Generated by Django 5.0.3 on 2024-03-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gereradorGrafico', '0002_alter_gereradorgrafico_dependenciaadministrativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gereradorgrafico',
            name='AnosFinais',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gereradorgrafico',
            name='AnosIniciais',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gereradorgrafico',
            name='Creche',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gereradorgrafico',
            name='NaoSeriado',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gereradorgrafico',
            name='PreEscola',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gereradorgrafico',
            name='TurmasMultietapa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gereradorgrafico',
            name='_1Ano',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gereradorgrafico',
            name='_1Serie',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gereradorgrafico',
            name='_2Ano',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gereradorgrafico',
            name='_2Serie',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gereradorgrafico',
            name='_3Ano',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gereradorgrafico',
            name='_3Serie',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gereradorgrafico',
            name='_4Ano',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gereradorgrafico',
            name='_4Serie',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gereradorgrafico',
            name='_5Ano',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gereradorgrafico',
            name='_6Ano',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gereradorgrafico',
            name='_7Ano',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gereradorgrafico',
            name='_8Ano',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gereradorgrafico',
            name='_9Ano',
            field=models.FloatField(),
        ),
    ]
